#!/usr/bin/env bash

p1='default value'
p2='default value'
p3='default value'

desc all param p1 p2 p3
task all {
  echo "$p1.$p2.$p3."
}

desc single param p2
task single {
  echo "$p1.$p2.$p3."
}

desc outer param p1
task outer {
  depends_on inner
}

desc inner param p2 p3
task inner {
  echo "$p1.$p2.$p3."
}
