#!/usr/bin/env bash
# Dogfooding... Using koshu to bake koshu.

sourceDir="${here:?}/src"
testDir="${here:?}/test"

testing=false
debug=true

desc global param testing

export KOSHU_SOURCE_DIR=$sourceDir

test () {
  declare -a tests=()
  while read -r x; do
    if [[ -d "$testDir/$x" ]]; then
      log "Adding '$x' tests to testrun ($testDir/$x/test.bats)"
      tests+=("$testDir/$x/test.bats")
    fi
  done <<<"$(ls "$testDir")"
  bats -p ${tests[*]}
}

desc test:docker purpose 'Used to run test in a docker container'
desc test:docker param debug
desc test:docker example '-p debug=false'

test:docker () {
  declare -a versions=('3.2.57' '4.0.44' '4.3.48')
  declare -a skipping=('3.0.22' '4.4.0')
  declare bats_dir
  declare current_dir

  for v in "${skipping[@]}"; do echo "Skipping bash $v"; done

  for v in "${versions[@]}"; do
    bats_dir="${here:?}/../bats:/bats"
    current_dir="${here:?}:/koshu-shell"

    echo && echo "Testing in bash $v"
    docker run --rm -v "$bats_dir" -v "$current_dir" "bash:$v" bash /koshu-shell/test/docker-run-test.sh

    if [[ $? != 0 ]] && [[ $debug == true ]]; then
      docker run --rm -it -v "$bats_dir" -v "$current_dir" "bash:$v" bash
    fi
  done
}

install () {
  sudo npm 'install' -g
}

uninstall () {
  sudo npm 'uninstall' -g
}
