#!/usr/bin/env bash
# Dogfooding... Using koshu to bake koshu.

sourceDir="${here:?}/src"
testDir="${here:?}/test"

export KOSHU_SOURCE_DIR=$sourceDir

task test {
  declare -a tests=()
  while read x; do
    if [[ -d "$testDir/$x" ]]; then
      verbose "Adding '$x' tests to testrun ($testDir/$x/test.bats)"
      tests+=("$testDir/$x/test.bats")
    fi
  done <<<"$(ls $testDir)"
  bats -p ${tests[*]}
}

task install {
  sudo npm 'install' -g
}

task uninstall {
  sudo npm 'uninstall' -g
}
