#!/usr/bin/env bash

task default {
  depends_on test
}

task setup {
  echo 'Setting up...'
  sleep 1
}

task compile {
  depends_on setup
  echo 'Compiling...'
  sleep 1
}

task test {
  depends_on compile
  echo 'Testing...'
  sleep 1
}
