#!/usr/bin/env bash

task default {
  log 'log_default'
  log_verbose 'log_verbose'
  log_success 'log_success'
  log_info 'log_info'
  log_warn 'log_warn'
  log_error 'log_error'
}

task color {
  color default 'color_default'
  color red 'red'
  color blue 'blue'
  color green 'green'
  color yellow 'yellow'
  color gray 'gray'
  color gray foo and bar
}
