#!/usr/bin/env bash

task default {
  verbose 'verbose'
  success 'success'
  info 'info'
  warn 'warn'
  error 'error'
}

task color {
  color red 'red'
  color blue 'blue'
  color green 'green'
  color yellow 'yellow'
  color gray 'gray'
  color gray foo and bar
}
