#!/usr/bin/env bash

task default {
  log 'log_default'
  log_verbose 'verbose'
  log_success 'success'
  log_info 'info'
  log_warn 'warn'
  log_error 'error'
}

task color {
  color default 'color_default'
  color red 'red'
  color blue 'blue'
  color green 'green'
  color yellow 'yellow'
  color gray 'gray'
  color gray foo and bar
}
