#!/usr/bin/env bash

p1='default value'
p2='default value'
p3='default value'

desc global param p1
desc global param p2

task global_only {
  echo "$p1.$p2.$p3."
}

desc global_and_specific param p3
task global_and_specific {
  echo "$p1.$p2.$p3."
}

desc specific_only param p4
task specific_only {
  echo "$p1.$p2.$p3.$p4."
}
